import React from 'react';
import {StyleSheet} from 'react-native';
import {scale} from 'react-native-size-matters';

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#ffffff',
  },
  mainInput: {
    borderColor: '#00000',
    borderWidth: scale(0.8),
    borderRadius: scale(6),
    position: 'relative',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-start',
    marginHorizontal: scale(5),
  },
  textInput: {
    marginLeft: scale(20),
  },
  search: {
    position: 'absolute',
    alignItems: 'flex-start',
    marginLeft: scale(5),
  },
  voiceIcon: {
    position: 'absolute',
    marginLeft: scale(310),
  },
  linearContent: {
    flexDirection: 'row',
    marginHorizontal: scale(5),
    marginVertical: scale(8),
    borderRadius: scale(8),
    height: scale(40),
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(5),
  },
  linear: {
    flex: 0,
    justifyContent: 'space-between',
    alignItems: 'center',
    // paddingHorizontal: scale(8),
    flexDirection: 'row',
  },
  LocationIcon: {
    height: scale(25),
    width: scale(25),
  },
  locationtxt: {
    fontSize: scale(15),
    // alignSelf: 'center',
    fontWeight: 500,
  },
  button: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'green',
    height: scale(30),
    borderRadius: scale(5),
  },
  btnText: {
    color: 'white',
    fontWeight: 500,
    paddingHorizontal: scale(5),
  },
  brandHeading: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: scale(10),
  },
  brand: {
    fontSize: scale(17),
    fontWeight: 700,
    // marginHorizontal: scale(10),
    marginVertical: scale(10),
  },
  link: {
    fontSize: scale(13),
    fontWeight: 600,
    marginVertical: scale(10),
  },
  card: {
    margin: scale(6),
  },
  images: {
    height: scale(85),
    width: scale(85),
    borderColor: '#CAD5E2',
    borderWidth: scale(4),
    borderRadius: scale(6),
  },
  texts: {
    width: scale(85),
    fontSize: scale(14),
    overflow: 'hidden',
    fontWeight: 500,
  },
  linearCard: {
    height: scale(120),
    width: scale(100),
    margin: scale(8),
    borderRadius: scale(8),
    justifyContent: 'space-between',
    alignItems: 'left',
    padding: scale(5),
  },
  box: {
    height: scale(170),
    backgroundColor: '#f5edc4',
    marginTop: scale(20),
  },
  categories: {
    fontSize: scale(17),
    fontWeight: 700,
    margin: scale(8),
  },
  img: {
    height: scale(85),
    width: scale(85),
    alignSelf: 'center',
  },
  title: {
    fontSize: scale(15),
    fontWeight: 700,
    color: '#692f2f',
  },
  form: {
    height: scale(500),
    backgroundColor: '#f2e22c',
    marginTop: scale(22),
    margin: scale(10),
    borderRadius: scale(12),
  },
  heading: {
    fontSize: scale(23),
    textAlign: 'center',
    marginTop: scale(18),
    fontWeight: 600,
  },
  para: {
    textAlign: 'center',
    marginTop: scale(3),
    fontSize: scale(13),
    fontWeight: 400,
  },
  dropdown: {
    margin: scale(12),
    height: scale(40),
    backgroundColor: '#ffffff',
    borderRadius: scale(5),
    marginBottom: scale(0),
    justifyContent: 'center',
  },
  placeholderStyle: {
    fontSize: scale(15),
    marginHorizontal: scale(10),
  },
  selectedTextStyle: {
    fontSize: scale(15),
    marginHorizontal: scale(10),
  },
  iconStyle: {
    width: scale(25),
    height: scale(25),
  },
  inputSearchStyle: {
    height: scale(35),
    fontSize: scale(13),
  },
  input: {
    backgroundColor: '#ffffff',
    height: scale(40),
    width: scale(145),
    margin: scale(14),
    borderRadius: scale(4),
    fontSize: scale(13),
    paddingHorizontal: scale(10),
    fontWeight: 500,
  },
  dropdown1: {
    height: scale(40),
    width: scale(145),
    margin: scale(16),
    marginLeft: scale(0),
    backgroundColor: '#ffffff',
    borderRadius: scale(4),
  },
  textareaContainer: {
    height: scale(130),
    width: scale(305),
    marginHorizontal: scale(14),
    backgroundColor: '#ffffff',
  },
  textarea: {
    textAlignVertical: 'top',
    height: scale(160),
    fontSize: scale(12),
    color: '#333',
  },
  btn: {
    backgroundColor: 'red',
    margin: scale(14),
    height: scale(35),
    borderRadius: scale(8),
    textAlign: 'center',
    justifyContent: 'center',
    textAlignVertical: 'center',
    fontSize: scale(15),
    color: '#ffffff',
    fontWeight: 700,
    shadowColor: '#000000',
    shadowOffset: {
      width: scale(0),
      height: scale(3),
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.5,
    elevation: 7,
  },
  btnadd: {
    position: 'absolute',
    height: scale(30),
    width: scale(150),
    borderRadius: scale(22),
    backgroundColor: '#f08d3a',
    justifyContent: 'center',
    alignItems: 'center',
    right: scale(12),
    bottom: scale(12),
  },
  btnAddRound: {
    position: 'absolute',
    height: scale(40),
    width: scale(40),
    borderRadius: scale(20),
    backgroundColor: '#f08d3a',
    justifyContent: 'center',
    alignItems: 'center',
    right: scale(12),
    bottom: scale(12),
    fontSize: scale(20),
  },
  blankView: {
    height: scale(100),
  },
  btnaddText: {
    fontSize: scale(17),
    color: '#ffffff',
    textAlign: 'center',
  },
});

export default styles;
