import {StyleSheet} from 'react-native';
import {scale} from 'react-native-size-matters';

const style = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  mainContent: {
    backgroundColor: 'white',
  },
  image: {
    height: scale(155),
    borderRadius: scale(15),
    marginTop: scale(8),
    resizeMode: 'cover',
    //   backgroundColor: '#e0e0de',
  },
  detail: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: scale(15),
    marginTop: scale(20),
  },
  detailDisplay: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // alignItems: 'center',
  },
  logoImg: {
    height: scale(60),
    width: scale(60),
    borderRadius: scale(30),
    borderColor: 'gray',
    borderWidth: scale(2),
  },
  content: {
    flexDirection: 'row',
    gap: scale(5),
  },
  verified: {
    flexDirection: 'row',
    gap: scale(5),
  },
  nameText: {
    fontSize: scale(15),
    fontWeight: 600,
  },
  nameContent: {
    marginHorizontal: scale(10),
    gap: scale(2),
  },
  manufacturerText: {
    backgroundColor: '#ccae04',
    color: '#000000',
    fontWeight: 500,
    borderRadius: scale(10),
    paddingHorizontal: scale(7),
    paddingVertical: scale(1),
  },
  ratingText: {
    backgroundColor: 'green',
    color: '#ffffff',
    fontWeight: 500,
    borderRadius: scale(10),
    paddingHorizontal: scale(7),
    paddingVertical: scale(1),
  },
  verifiedText: {
    color: '#527582',
    fontStyle: 'italic',
    fontSize: scale(12),
    fontWeight: 600,
  },
  sponsoredText: {
    color: '#d17e02',
    fontStyle: 'italic',
    fontSize: scale(12),
    fontWeight: 600,
  },
  Icon: {
    flexDirection: 'row',
    gap: scale(25),
    justifyContent: 'space-between',
    margin: scale(20),
  },
  iconContent: {
    justifyContent: 'center',
    alignItems: 'center',
    gap: scale(5),
  },
  activeIcon: {
    backgroundColor: '#34a1eb',
    height: scale(35),
    width: scale(35),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(8),
  },
  notActiveIcon: {
    backgroundColor: '#cbcfd1',
    height: scale(35),
    width: scale(35),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(8),
    shadowColor: '#000000',
    shadowOffset: {
      width: scale(0),
      height: scale(3),
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.5,
    elevation: 7,
  },
  rateContent: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: scale(8),
  },
  rateText: {
    fontSize: scale(15),
    fontWeight: 600,
  },
  descriptionText: {
    color: '#08505e',
    fontSize: scale(16),
    fontWeight: 700,
    // marginTop: scale(10),
  },
  line: {
    borderColor: 'gray',
    borderWidth: scale(0.3),
    width: scale(230),
  },
  aboutText: {
    fontSize: scale(14),
    color: '#585b5c',
    marginHorizontal: scale(10),
  },
  specificationCard: {
    marginTop: scale(10),
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    // justifyContent: 'space-between',
    paddingHorizontal: scale(15),
    gap: scale(10),
    height: scale(60),
    marginHorizontal: scale(10),
    borderRadius: scale(10),
    shadowColor: '#000000',
    shadowOffset: {
      width: scale(0),
      height: scale(3),
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.5,
    elevation: 7,
  },
  iconBG: {
    height: scale(25),
    width: scale(25),
    borderRadius: scale(12),
    backgroundColor: '#40a1c7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  wpIconBG: {
    height: scale(25),
    width: scale(25),
    borderRadius: scale(12),
    backgroundColor: '#288f69',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emailIconBG: {
    height: scale(25),
    width: scale(25),
    borderRadius: scale(12),
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    height: scale(200),
    width: scale(155),
    borderColor: '#ddd',
    borderWidth: scale(1),
    borderRadius: scale(12),
    marginHorizontal: scale(10),
    marginVertical: scale(10),
  },
  catalogueImage: {
    height: scale(100),
    width: scale(154),
    borderTopLeftRadius: scale(12),
    borderTopRightRadius: scale(12),
  },
  catalogueName: {
    width: scale(140),
    fontSize: scale(15),
    overflow: 'hidden',
    fontWeight: 500,
    marginHorizontal: scale(5),
    marginTop: scale(8),
  },
  catalogueSize: {
    width: scale(140),
    fontSize: scale(11),
    overflow: 'hidden',
    marginHorizontal: scale(5),
    color: 'gray',
  },
  catalogueType: {
    width: scale(140),
    fontSize: scale(11),
    overflow: 'hidden',
    marginHorizontal: scale(5),
  },
  bottomColor: {
    backgroundColor: '#e6e8ed',
    height: scale(28),
    marginTop: scale(19),
    borderBottomRightRadius: scale(12),
    borderBottomLeftRadius: scale(12),
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: scale(10),
  },
  views: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: scale(10),
    gap: scale(5),
  },
  viewsText: {
    color: 'gray',
    fontSize: scale(14),
  },
});

export default style;
